// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2JPHL-4dHtBYdV7q87wvK8GyUU6svt3c',
    appId: '1:247484595086:web:f427c5c751513353c442df',
    messagingSenderId: '247484595086',
    projectId: 'recipe-app-ecd37',
    authDomain: 'recipe-app-ecd37.firebaseapp.com',
    storageBucket: 'recipe-app-ecd37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDma_jOVS7LagG2FrjCNhh2OW4MlN5mRkw',
    appId: '1:247484595086:android:93dabec864ec77e4c442df',
    messagingSenderId: '247484595086',
    projectId: 'recipe-app-ecd37',
    storageBucket: 'recipe-app-ecd37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCRtwybq07GOhedvtQ7YwSYyhNbP4qgko',
    appId: '1:247484595086:ios:63ee626615d96348c442df',
    messagingSenderId: '247484595086',
    projectId: 'recipe-app-ecd37',
    storageBucket: 'recipe-app-ecd37.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2JPHL-4dHtBYdV7q87wvK8GyUU6svt3c',
    appId: '1:247484595086:web:69a4b507dfa95899c442df',
    messagingSenderId: '247484595086',
    projectId: 'recipe-app-ecd37',
    authDomain: 'recipe-app-ecd37.firebaseapp.com',
    storageBucket: 'recipe-app-ecd37.firebasestorage.app',
  );
}
